### ISSUE TITLE
FAQ - what is the differentiator from angular-busy?

### ISSUE THREAD

**Issue by pulkitsinghal** [maximnaidenov/angular-busy-tracker#1]

**Comment by maximnaidenov** [comment]
Main difference are the flexible templates. By default you get an overlay spinner and spinner inside a button templates. They both use pure CSS3 animated spinner with glyphicon-spin. And I have examples how to use spin.js for the popular bar spinner and how to create a new template that shows the spinner next to a button.
And there is a nice small feature - busy ready expression. I personally use it to navigate away from a "saving" dialog.

**Comment by pulkitsinghal** [comment]
I'd like to hear more about `busy ready expression` could you elaborate? I'm not sure I understood.

**Comment by maximnaidenov** [comment]
You know about angular expressions, those are the code snippets that you put in ng-click for example. They are evaluated (executed) when the specified action happens. So I have busy-ready attribute that accepts an expression that will be evaluated when the tracked promise is resolved or rejected.
Imagine a form saving button that executes a REST API call. You want to have a spinner in the button while the saving operations is pending but when the backend is ready you may want to directly dismiss the form. So you could achieve this with an expression in the busy-ready attribute.

**Comment by pulkitsinghal** [comment]
Awesome, one last suggestion, would you mind setting up a free/dedicated chat room for this project: https://gitter.im/maximnaidenov/angular-busy-tracker ?
